[Data]Fix none issue if set DATA_ENABLE_OP_RESOURCE_RESERVATION=False (#61718)
Ray Data will raise the following error

> return self._op_resource_allocator.max_task_output_bytes_to_read(op)
AttributeError: 'NoneType' object has no attribute
'max_task_output_bytes_to_read'

if set RAY_DATA_ENABLE_OP_RESOURCE_RESERVATION=False

---------

Signed-off-by: yifan.xie <xyfabcd@163.com>
Co-authored-by: You-Cheng Lin <106612301+owenowenisme@users.noreply.github.com>
(cherry picked from commit 597bb262fbcf151f2c1aeb3d245f40ac560096a0)
Signed-off-by: OneSizeFitsQuorum <tanxinyu@apache.org>